### ISSUE TITLE
Some problems of make operation

### ISSUE THREAD

**Issue by robinren03** [BDHU/CUDA_Device_Attribute_Generation#1]
Hi, when I ran make, the compiler gives out the following instruction:
> deviceQuery.cpp: In function ‘int main(int, char**)’:
> deviceQuery.cpp:167:24: error: ‘stoi’ is not a member of ‘std’
>   int deviceToQuerry = std::stoi(std::string(argv[2]));
>                                  ^
> deviceQuery.cpp:172:68: error: no matching function for call to ‘std::basic_fstream<char>::open(std::__cxx11::string&, std::_Ios_Openmode)’
>  cudaHdrFile.open(hdrPath, std::fstream::out | std::fstream::trunc);
>                                                                    ^

What's the problem and how should I deal with it ?

**Comment by BDHU** [comment]
What OS, compiler, and compiler version are you using? stoi uses libstdc++. In gcc you have to link adding -lstdc++. However, in g++, libstdc++ is linked automatically. Also std::stoi is a C++11 function.

**Comment by robinren03** [comment]
> What OS, compiler, and compiler version are you using? stoi uses libstdc++. In gcc you have to link adding -lstdc++. However, in g++, libstdc++ is linked automatically. Also std::stoi is a C++11 function.

Thank you , maybe I should update my compiling tool.
